# Generated by Django 3.1.2 on 2020-10-20 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='intial_deposit',
            new_name='initial_deposit',
        ),
    ]
